; A193213: Primes generated by the golden sieve, cf. A099267.
; Submitted by Simon Strandgaard
; 2,3,5,11,13,19,23,29,31,37,47,53,61,71,73,79,89,97,103,107,113,131,137,139,149,157,163,167,173,179,181,191,197,199,223,233,239,241,251,257,277,281,283,293,307,311,317,349,353,359,367,379,383,401,409,419

mov $2,$0
pow $2,2
lpb $2
  add $6,1
  mov $3,$6
  seq $3,10051 ; Characteristic function of primes: 1 if n is prime, else 0.
  sub $0,$3
  add $1,8
  mov $4,$0
  max $4,0
  cmp $4,$0
  mul $2,$4
  sub $2,1
  div $5,18
  add $5,$1
  div $5,5
  mov $6,$5
lpe
mov $0,$6
add $0,2
